### ISSUE TITLE
[1pts] CREATE INTIAL SCHEMA FOR ALL TABLES

### ISSUE THREAD

**Issue by AbelG101** [AbelG101/Recipe-app#11]
- Add migration for **User table**, with the following columns:
    - name :string
- Add migration for **Food table**, with the following columns:
    - name :string
    - measurement_unit :number
    - price :number
    - quantity :number
    - user_Id :number [FK]
- Add migration for **Recipe table**, with the following columns:
    - name :string
    - preparation_time :number
    - cooking_time :number
    - description :string
    - public :boolean
    - user_Id :number [FK]
- Add migration for **Recipe Food table**, with the following columns:
    - quantity :number
    - measurement_unit :number
    - recipe_Id :number [FK]
    - food_Id :number [FK]

**Comment by betses** [comment]
This Issue is done on #13
